"""feat(exercises): add muscle_coefficients

Revision ID: 431ef3a75417
Revises: f9d86bb54948
Create Date: 2025-11-07 14:28:31.880769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '431ef3a75417'
down_revision: Union[str, Sequence[str], None] = 'f9d86bb54948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # СНАЧАЛА удаляем внешний ключ, который ссылается на equipment
    op.drop_constraint('exercises_equipment_id_fkey', 'exercises', type_='foreignkey')
    
    # Затем удаляем столбец equipment_id из exercises
    op.drop_column('exercises', 'equipment_id')
    
    # Теперь можно безопасно удалить таблицу equipment
    op.drop_index('ix_equipment_id', table_name='equipment')
    op.drop_index('ix_equipment_name', table_name='equipment')
    op.drop_table('equipment')
    
    # Добавляем новый столбец muscle_coefficients
    op.add_column('exercises', sa.Column('muscle_coefficients', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Удаляем остальные старые столбцы
    op.drop_column('exercises', 'optimal_reps_max')
    op.drop_column('exercises', 'muscle_group')
    op.drop_column('exercises', 'optimal_reps_min')
    op.drop_column('exercises', 'exercise_metadata')
    op.drop_column('exercises', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Сначала восстанавливаем старые столбцы (кроме equipment_id)
    op.add_column('exercises', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('exercise_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('optimal_reps_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('muscle_group', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('optimal_reps_max', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Восстанавливаем таблицу equipment
    op.create_table('equipment',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column('base_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('min_increment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column('available_weights', sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='equipment_pkey')
    )
    op.create_index('ix_equipment_name', 'equipment', ['name'], unique=True)
    op.create_index('ix_equipment_id', 'equipment', ['id'], unique=False)
    
    # Восстанавливаем столбец equipment_id и внешний ключ
    op.add_column('exercises', sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exercises_equipment_id_fkey', 'exercises', 'equipment', ['equipment_id'], ['id'])
    
    # Удаляем новый столбец muscle_coefficients
    op.drop_column('exercises', 'muscle_coefficients')
    # ### end Alembic commands ###